name: genopro
title: GenoPro
base: core20
version: "3.1.0.1" # Based on the installed GenoPro version number
summary: The best genealogy software for drawing family trees and genograms.
description: |
  GenoPro is a software application for drawing family trees and genograms.
  It can store additional information such as pictures, contacts, places,
  sources, occupation and education history for each individual, as well as
  document the relationships among individuals.

  GenoPro is not a free application. Prices can be found at
  https://genopro.com/buy/
  Registration can also
  be done through the application itself.

  This package is an unofficial packaging of Genopro using the Sommelier plug
  provided by Snapcrafters.

  Accessing external meda requires providing additional permission. If you need
  to do this, provide this app with removable media access through your software
  store or run:
    snap connect genopro:removable-media

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - amd64
  - i386
compression: lzo
assumes:
  - snapd2.55
  - common-data-dir
contact: https://github.com/lengau
issues: https://github.com/lengau/genopro/issues
icon: images/genopro-512.png
license: Proprietary
source-code: https://github.com/lengau/genopro
website: https://genopro.com

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_KEEP_CWD: "1" # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session by using Xwayland
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core20
  # Guarantee installation of the cups interface. See: https://snapcraft.io/docs/cups-interface
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo

parts:
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"

apps:
  genopro:
    extensions: [gnome-3-38]
    command: bin/sommelier run-exe
    environment:
      WINEARCH: win32
      RUN_EXE: C:/GenoPro/GenoPro.exe
      INSTALL_URL: https://genopro.com/archives/InstallGenoPro.3.1.0.1.exe
      INSTALL_FLAGS: /USilent /ND /path "C:\GenoPro"
      TRICKS: vcrun6 cjkfonts corefonts tahoma
    plugs:
      - home
      - network
      - removable-media
      - cups
  wine:
    extensions: [gnome-3-38]
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks
    plugs:
      - home
      - network
